oracle/ojdbc-extensions

ojdbc-provider-azure/README.md, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/resource/AzureTokenProviderTest.java, ojdbc-provider-oci/pom.xml, ojdbc-provider-oci/src/test/java/oracle/jdbc/provider/oci/configuration/OciDatabaseToolsConnectionProviderTest.java, pom.xml
Resolving some issues I found when testing.
- The ojdbc-provider-common test jar dependency had a now non-existent SNAPSHOT version in a few poms. I've made the version the same as the project version.
- README had an incorrect URL for common resource provider parameters.
- An Azure access token provider test for managed identity did not configure managed identity.
- A database tools test would fail test runs if no configuration file was present. It will now just indicate that the test was skipped and ignored.
- A database tools test would NPE if required test.properties were missing. It will now be a no-op.
=> Test Fixes

ojdbc-provider-oci/README.md
Correcting the link that jumps to common parameters for resource providers. Also removing duplicated punctuation..
=> Correcting Fragment URL for resource provider

pom.xml
This pull request adds LICENSE.txt and THIRD_PARTY_LICENSE.txt to META-INF directory in each jar.
All modules in this project share the same LICENSE.txt which locates at the root directory of this project.
Each module has its own THIRD_PARTY_LICENSE.txt which locates at the base directory of the module.
=> add LICENSE.txt and THIRD_PARTY_LICENSE.txt

pom.xml
From Mohamed:
There are some issues with the artifacts
POM file
Invalid POM: /com/oracle/database/jdbc/ojdbc-extensions/1.0.0/ojdbc-extensions-1.0.0.pom: Project description missing, Project URL missing, License information missing, SCM URL missing, Developer information missing
Update the project pom file and fill in the missing fields.
=> update project description, url, license info, and developer url

pom.xml
The META-INF/services would not be picked up by maven automatically after adding the `<resources></resources>` section. Added an entry in the resources section of pom.xml to include the files in META-INF/services when building the artifacts.
=> add META-INF/services

ojdbc-provider-oci/pom.xml
- Update the version of oci-java-sdk to 3.28.1:
The SBOM scan report showed the following issue:
OCI Java SDK - [CVE-2023-33201] CWE-295: Improper Certificate Validation
pkg:maven/com.oracle.database.jdbc/ojdbc-provider-oci@1.0.0
pkg:maven/com.oracle.oci.sdk/oci-java-sdk-common@3.2.2
pkg:maven/org.bouncycastle/bcprov-jdk15on@1.70
This issue in BouncyCastle is fixed versions: BC 1.74 but OCI Java SDK 3.2.2 consumes 1.70.
OCI SDK 3.28.1 consumes BC 1.74. So it looks like we should upgrade the OCI SDK from 3.2.2 to 3.28.1.
- Removes the version tag of oraclepki in ojdbc-provider-oci/pom.xml. The dependency oraclepki should reuse the version which is inherited from the parent pom and avoid specifying its own in the pom file.
=> Update oci sdk version

pom.xml
This branch sets the maven.compiler.release setting to 8. This avoids sneaky runtime failures that can happen when a new JDK version is compiling our code. For instance, calls to CharBuffer.clear() break if compiled by a JDK newer than 8, and then run on JDK 8. This is because the return type of the clear() method changed after JDK 8, and our users will hit:
```
java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
at oracle.jdbc.provider.oci.vault.Secret.toCharArray(Secret.java:99)
```
Setting the release option ensures that byte code is consistent with the API of the specified JDK 8. With this CharBuffer example, it ensures that byte code calls a method with a `Buffer` return type, rather than `CharBuffer`. 
The release option is documented here: …
=> Set Release to JDK 8

pom.xml
This branch sets the Maven Compiler Plugin to version 3.11.0.
This branch is a follow up to https://github.com/oracle-samples/ojdbc-extensions/pull/46, which configured Maven with a release option for javac. It seems that this configuration is not be supported with older versions of the compiler plugin, such as 3.6. The latest version is 3.11, so I've updated to that.
I also reverted changes to Maven's source and target properties, setting them as "1.8" rather than "8". All examples I see in Maven documentation use "1.8" for these properties. However, examples will also use "8" for the release property, so I think the same JDK version needs to expressed differently, depending on which property is being set.
=> Maven Compiler Plugin 3.11

ojdbc-provider-oci/pom.xml
The extension set oci-java-sdk-common-httpclient-jersey as a compile dependency, which should be set as a runtime dependency instead. 
More details below:
Starting from OCI Java SDK 3.x.x, users have to explicitly choose the http provider in their application, otherwise they will get the error message: `No http provider available; add dependency on one of the oci-java-sdk-common-httpclient-* choices, e.g. oci-java-sdk-common-httpclient-jersey.`
The extension selects oci-java-sdk-common-httpclient-jersey as the http provider so that the users don't have to worry if the http provider is not configured. Users can override the dependency with their own choice later in their pom file.
=> Set oci-java-sdk-common-httpclient-jersey as Runtime Dependency

ojdbc-provider-oci/README.md, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciDatabaseToolsConnectionProvider.java
In this upload, the provider can accept db tools connection with proxy authentication, only if username is set in proxy authentication, without password or roles.
Specifically, according to [OCI docs](https://docs.oracle.com/en-us/iaas/tools/java/3.29.0/com/oracle/bmc/databasetools/model/DatabaseToolsConnectionOracleDatabaseProxyClient.html), 
`DatabaseToolsConnectionOracleDatabaseProxyClient` has two direct known subclasses,
which is `DatabaseToolsConnectionOracleDatabaseProxyClientNoProxy`, and 
`DatabaseToolsConnectionOracleDatabaseProxyClientUserName`.
If a db tools connection with proxy authentication is given, we can retrieve proxy authentication info from `proxyClientUserName`. Otherwise, we will get `proxyClientNoProxy`.
Username is retrieved here and added to properties of the …
=> Accept db tools conn with proxy authentication

ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/Ocid.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/databasetools/DatabaseToolsConnectionFactory.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/vault/SecretFactory.java
In this upload, a new Class Ocid is created. We can use the constructor to create an Ocid object:
`Ocid ocid = new Ocid(ocidString);`
And retrieve ocid string using `ocid.getContent()`,
retrieve region using `ocid.getRegion().`
The parser in Class Ocid parse the region from string ocid. This region can be empty, considering that in some cases, an ocid string does not represent regional resources.
In this upload, database tools connection and secret are using the new Ocid Class to parse region and set region to resolve multi region issue. (Recall multi region issue: there is region 'us-XXX-1' in profile, but we want to support resources in other regions, without changing the profile)
When building the client to send request, the region of client is set by
`client.setRegion(ocid.getRegion)` …
=> 38 multi region support in oci

ojdbc-provider-azure/pom.xml, ojdbc-provider-oci/pom.xml
For the next release (v1.0.1), upgrade Azure and OCI JDKs to latest versions:
- azure-sdk-bom from 1.2.17 to `1.2.19` ([ojdbc-extensions](https://github.com/oracle-samples/ojdbc-extensions/tree/main)/[ojdbc-provider-azure](https://github.com/oracle-samples/ojdbc-extensions/tree/main/ojdbc-provider-azure)
/pom.xml) 
`1.2.19` will also address the new vulnerability CVE-2023-34054.
- oci-java-sdk-bom from 3.28.1 to `3.30.0`
=> upgrade Azure and OCI SDKs

ojdbc-provider-azure/README.md, ojdbc-provider-azure/example-key-vault.properties, ojdbc-provider-azure/example-token.properties, ojdbc-provider-oci/README.md
This branch updates URL links to the Oracle JDBC JavaDoc. These links appear in README's and in example connection property files. Some links were going to the OJDBC 21.x release. These are now updated to the 23.x release.
=> Updating JavaDoc links to 23

.gitignore, ojdbc-provider-azure/README.md, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/authentication/TokenCredentialFactory.java
This branch changes the redirect URI parameter for interactive authentication with Azure. The parameter is now optional. If users do not configure this parameter, the Azure SDK for Java will use a localhost URL having any available port number in the ephemeral range. For example, the SDK might use `http://localhost:52741`.
This change eases the burden of configuration for our users. They will no longer need to configure a redirect URI, on top of all the other configurable values. Users only need to add a localhost URI in their Azure App Registration, and it will match with a localhost URI having any port number used by clients (https://learn.microsoft.com/en-us/entra/identity-platform/reply-url#localhost-exceptions)
=> Redirect URI is Optional

ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureVaultJsonProviderTest.java
Considering that we cannot assume the testing environment always has the setups in advance, add getOrAbort() for required variables to prevent test failure
The test will abort instead of fail, in the situation that the required variables are not set.
=> Fix for Azure Vault Provider test: Add getOrAbort() for required variables to prevent test failure

ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureVaultSecretProvider.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureVaultSecretProviderTest.java, ojdbc-provider-oci/README.md, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciVaultSecretProvider.java
Type names of existing secret providers `AzureVaultSecretProvider` and ` OciVaultSecretProvider`, are changed.
Specifically, the type name of `AzureVaultSecretProvider` is changes from "vault-azure" to "azurevault".
The type name of ` OciVaultSecretProvider` is changed from "vault-oci" to "ocivault".
This change is for the consistency with the type names of the newly-added json providers ( `AzureVaultJsonProvider` and `OciVaultJsonProvider` ).
The type names are also changed in test accounts accordingly. So if you want to run the Github workflow recently, please git pull the latest changes or cherry-pick it from this branch, to make the workflow work. Thanks!
Please take a look.
=> Change type names of existing secret provider to "azurevault" and "ocivault"

ojdbc-provider-azure/README.md, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProvider.java, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureVaultJsonProvider.java, ojdbc-provider-oci/README.md, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciDatabaseToolsConnectionProvider.java
Update README.mds to add more contents for the caching of configuration. Renaming the constants `MS_TIMEOUT` and `MS_REFRESH_INTERVAL` add adding javadoc to be more descriptive. 
I've also made minor changes in the README.mds. You can compare the difference by clicking "Display the rich diff" besides the three dots icon. Please let me know if you have any thoughts on the changes. Thanks.
=> updating doc for configuration cache

ojdbc-provider-oci/example-vault.properties
The example connection properties file was just completely wrong. This branch corrects it.
=> Correcting Example for Vault Username and Password Provider

ojdbc-provider-azure/pom.xml
Using AZURE_DEFAULT authentication with AZURE_USERNAME and AZURE_PASSWORD failed to acquire token. This is a defect in our `azure-identity` dependency. Upgrading to the latest `azure-bom-sdk` of version 1.2.24 fixes the issue.
=> Upgrade to the latest version of azure-bom-sdk

ojdbc-provider-opentelemetry/src/main/java/oracle/jdbc/provider/opentelemetry/OpenTelemetryTraceEventListener.java, ojdbc-provider-opentelemetry/src/main/java/oracle/jdbc/provider/opentelemetry/OpenTelemetryTraceEventListenerMBean.java, ojdbc-provider-opentelemetry/src/test/java/oracle/jdbc/provider/opentelemetry/OpenTelemetryTraceEventListenerTest.java
This changes allow to use the MBean to set the tracer instead of retrieving it from GlobalOpenTelemetry.get().getTracer(...).
=> Add tracer to MBean Configurataion

ojdbc-provider-azure/README.md, ojdbc-provider-azure/example-key-vault-wallet.properties, ojdbc-provider-azure/example-test.properties, ojdbc-provider-azure/example-vault-wallet.properties, ojdbc-provider-azure/pom.xml, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/resource/KeyVaultSEPSProvider.java, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/resource/KeyVaultSecretProvider.java, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/resource/KeyVaultTCPSProvider.java, ojdbc-provider-azure/src/main/resources/META-INF/services/oracle.jdbc.spi.PasswordProvider, ojdbc-provider-azure/src/main/resources/META-INF/services/oracle.jdbc.spi.TlsConfigurationProvider, ojdbc-provider-azure/src/main/resources/META-INF/services/oracle.jdbc.spi.UsernameProvider, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/AzureTestProperty.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/resource/KeyVaultSEPSProviderTest.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/resource/KeyVaultTCPSProviderTest.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/CommonParameters.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/ResourceParameterUtils.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/TlsUtils.java, ojdbc-provider-oci/example-test.properties, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/VaultSEPSProvider.java
This PR adds support for TCPS Wallet Provider and SEPS (Secure External Password Store) Wallet Provider for Azure Key Vault, enhancing security for Oracle JDBC connections in Azure environments. The TCPS Wallet Provider enables secure retrieval and management of Base64-encoded wallets (PKCS12, SSO and PEM) from Azure Key Vault for mutual TLS (mTLS) communication with Oracle Autonomous Database. The SEPS Wallet Provider retrieves SEPS wallets from Azure Key Vault, securely extracting database credentials. These features extend Oracle JDBC’s functionality in Azure, similar to what is available for OCI Vault.
Fixes Issue: #102
=> 102 azure tcps seps wallet support

ojdbc-provider-samples/src/main/java/oracle/jdbc/provider/oci/configuration/resource/SimpleDatabaseConnectionStringProviderExample.java
This PR introduces a sample demonstrating the usage of the Database Connection String Provider and TLS Provider to securely connect to an Oracle Autonomous Database in OCI. The sample includes configuration properties for retrieving the connection string and TLS credentials from OCI, enabling secure mTLS connections with the database.
=> Add example for Database Connection String Provider

.github/workflows/run-tests.yaml, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProvider.java, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureVaultJsonProvider.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProviderURLParserTest.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/configuration/GcpCloudStorageConfigurationProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/configuration/GcpSecretManagerConfigurationProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciDatabaseToolsConnectionProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciObjectStorageProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/configuration/OciVaultJsonProvider.java, pom.xml
- Upgraded the version of ojdbc8 to 23.6.0.24.10.
- Changed the type of OracleConfigurationCache in AzureAppConfigurationProvider to private static final so that the providers created in different threads can access the same cache. The same has already be done in the other providers, I'm not sure why we missed this one.
- Updated AzureAppConfigurationProviderURLParserTest to ensure that the configuration is removed from the cache when each tests begins.
=> Tinglwan upgrade ojdbc 23.6.0.24.10

ojdbc-provider-common/src/main/java/oracle/jdbc/provider/resource/AbstractResourceProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/DatabaseConnectionStringProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/DatabaseTlsProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/OciResourceProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/VaultPasswordProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/VaultSEPSProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/VaultTCPSProvider.java, ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/resource/VaultUsernameProvider.java, ojdbc-provider-oci/src/test/java/oracle/jdbc/provider/oci/OciTestProperty.java, ojdbc-provider-oci/src/test/java/oracle/jdbc/provider/oci/resource/VaultUsernameProviderTest.java
This PR refactors the OCI providers to centralize **secret** and **wallet** retrieval logic by introducing shared `getSecret` and `getWallet` methods in `OciResourceProvider`. The `getSecret` method consolidates secret retrieval from OCI Vault, while `getWallet` centralizes wallet retrieval from the Autonomous Database (ADB) service. These changes reduce code duplication and improve maintainability by ensuring consistent handling of secrets and wallets across providers.
Additionally, this PR adds a missing test for `VaultUsernameProvider`, enhancing test coverage and verifying that usernames are correctly retrieved from OCI Vault.
issue : #113
=> Oci secret retrieval refactor username test

ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/resource/KeyVaultConnectionStringProviderTest.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/CommonParameters.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/FileUtils.java, ojdbc-provider-common/src/main/java/oracle/jdbc/provider/util/WalletUtils.java, ojdbc-provider-gcp/README.md, ojdbc-provider-gcp/example-test.properties, ojdbc-provider-gcp/example-vault.properties, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerConnectionStringProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerSEPSProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerTCPSProvider.java, ojdbc-provider-gcp/src/main/resources/META-INF/services/oracle.jdbc.spi.ConnectionStringProvider, ojdbc-provider-gcp/src/test/java/oracle/provider/gcp/resource/GcpSecretManagerConnectionStringProviderTest.java, ojdbc-provider-samples/src/main/java/oracle/jdbc/provider/gcp/resource/SimpleConnectionStringProviderExample.java
This PR adds support for storing and retrieving tnsnames.ora files in Google Cloud Platform (GCP) Secret Manager, allowing Oracle JDBC users to securely configure connection strings based on specified aliases. This enhancement brings GCP users the same secure connection configuration options previously available only in Azure Key Vault, expanding Oracle JDBC’s compatibility across cloud platforms. The PR includes tests to verify functionality and a sample to demonstrate configuration and usage for GCP environments.
issue: #114
=> Add GCP Secret Manager Connection String Provider for Oracle JDBC

ojdbc-provider-azure/README.md, ojdbc-provider-azure/example-key-vault.properties, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/resource/KeyVaultConnectionStringProvider.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/resource/KeyVaultConnectionStringProviderTest.java, ojdbc-provider-samples/src/main/java/oracle/jdbc/provider/azure/configuration/resource/SimpleConnectionStringProviderAzureExample.java
This PR updates the **Azure** provider by renaming the `tns-alias` parameter to` tnsAlias` to ensure consistency with other parameters. Changes include updates to the provider code, tests, and documentation to reflect the new name. Sample tests and the README have also been updated to provide clear information for users. These changes improve parameter naming consistency and simplify usage.
=> Rename tns-alias to tnsAlias in Azure Provider for Consistency

ojdbc-provider-azure/README.md
The README listed `redirectUrl` [but the code recognizes `redirectUri`](https://github.com/oracle/ojdbc-extensions/blob/f86022d0896891561fcba7bc7f1c43d89bc86556/ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/resource/AzureResourceProvider.java#L67).
=> Correcting redirectUri parameter name

ojdbc-provider-opentelemetry/README.md
Added system properties to README file
=> Updated readme file

ojdbc-provider-jackson-oson/README.md
Add the JAVA type to OSON type mapping in readme.
=> Update README.md to add the java type and OSON type mappings.

ojdbc-provider-jackson-oson/README.md, ojdbc-provider-jackson-oson/src/main/java/oracle/jdbc/provider/oson/OsonGenerator.java, ojdbc-provider-jackson-oson/src/test/java/oracle/jdbc/provider/oson/model/Employee.java, ojdbc-provider-jackson-oson/src/test/java/oracle/jdbc/provider/oson/model/EmployeeInstances.java, ojdbc-provider-jackson-oson/src/test/java/oracle/jdbc/provider/oson/test/MultiThreadTest.java
Save java.util.Date as "OSON TIMESTAMP" to preserve Time part of the Date.
=> Save java.util.Date as "OSON TimeStamp" to preserve Time part.

ojdbc-provider-azure/README.md, ojdbc-provider-oci/README.md, ojdbc-provider-opentelemetry/README.md
This PR updates the README files for the OCI, Azure, and OpenTelemetry providers to reflect the latest version `1.0.2`.
=> Update README files to reflect version 1.0.2

ojdbc-provider-azure/README.md
Corrected some typos and clarified that wallet files must be encoded as base64 when stored as a secret.
Added links to the OracleResourceProvider JavaDoc.
=> Improved README for Azure wallet providers

ojdbc-provider-oci/README.md
Clarified that wallet files must be encoded as base64 when stored as a secret. Added links to the OracleResourceProvider JavaDoc.
=> Improved README for OCI wallet providers

ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProviderURLParserTest.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureVaultSecretProviderTest.java
In some of the Azure tests `OracleConfigurationProvider.find()` are called outside of the driver code, and the provider is not yet added to the list of the allowed configuration provider at this point. Hence we need to add those providers manually in the test codes.
=> Fix "Provider: azure not enabled through: oracle.jdbc.configurationProviders" error

ojdbc-provider-aws/src/main/java/oracle/jdbc/provider/aws/resource/SecretsManagerConnectionStringProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerConnectionStringProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerSEPSProvider.java, ojdbc-provider-gcp/src/main/java/oracle/jdbc/provider/gcp/resource/GcpSecretManagerTCPSProvider.java
This PR refactors the AWS and GCP provider modules to use `decodeIfBase64` for Base64 decoding, eliminating duplicated decoding logic. 
The changes apply to `SecretsManagerConnectionStringProvider` (AWS) and GCP resource providers (`GcpSecretManagerConnectionStringProvider`, `GcpSecretManagerSEPSProvider`, `GcpSecretManagerTCPSProvider`),
=> Centralize Base64 decoding in AWS and GCP providers

ojdbc-provider-oci/src/main/java/oracle/jdbc/provider/oci/authentication/AuthenticationDetailsFactory.java, ojdbc-provider-oci/src/test/java/oracle/jdbc/provider/oci/AuthenticationDetailsFactoryTest.java
Fixes #159 
When some OCI API Key parameters (like OCI_USER or OCI_TENANCY) are provided without the full set, an IllegalStateException was thrown.
This update changes the logic to check if all required fields (TENANCY, USER, FINGERPRINT, PRIVATE_KEY) are present. If not, it falls back to config file authentication instead of throwing an exception.
Also added a test case to verify this behavior.
=> Fix fallback to config file when partial OCI API Key credentials are provided (Fixes #159)

ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/authentication/TokenCredentialFactory.java, ojdbc-provider-azure/src/main/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProvider.java, ojdbc-provider-azure/src/test/java/oracle/jdbc/provider/azure/configuration/AzureAppConfigurationProviderTest.java
Fixes: #195 
When a required Azure App Configuration parameter is missing or the URL is invalid, the driver previously threw unclear runtime exceptions. This update now detects missing or malformed parameters early and throws a concise SQLException indicating the bad configuration. A new unit test verifies that an empty or invalid URL fails fast with the expected SQLException.
=> Improve Azure App Configuration error handling

ojdbc-provider-oci/README.md
For sometime, resource providers have supported a "region" parameter. However, this parameter was never documented. This parameter is especially important for interactive authentication, which may fail when connecting to the default https://login.oci.oraclecloud.com endpoint (government regions require a different endpoint).
This branch simply updates the README to list "region" as a common parameter for resource providers, and explain how it can effect interactive authentication.
=> Documenting the region parameter for resource providers
